server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    db1:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345678
      # spring2.0此处为jdbc-url
      jdbc-url: jdbc:mysql://localhost:3306/ax_java_demo?characterEncoding=utf-8
      type: com.alibaba.druid.pool.DruidDataSource
    db2:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345678
      # spring2.0此处为jdbc-url
      jdbc-url: jdbc:mysql://localhost:3306/ax_shop?characterEncoding=utf-8
      type: com.alibaba.druid.pool.DruidDataSource



