server:
  servlet:
    context-path: /
  port: 8080

spring:
  application:
    name: springboot-dubbo-consumer

dubbo:
  application:
    name: springboot-dubbo-consumer #应用名
  registry:
    address: zookeeper://localhost:2181 #zookeeper地址
