server:
  servlet:
    context-path: /
  port: 8080

spring:
  messages:
    encoding: UTF-8
  profiles:
    active: db

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    check-template-location: true # 检查模板是否存在，然后再呈现
    enabled: true #启用MVC Thymeleaf视图分辨率
    template-resolver-order: 0
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8

  redis:
    password: # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    pool:
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    host: localhost # Redis服务器地址
    timeout: 5000 # 连接超时时间（毫秒）

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR