server:
  servlet:
    context-path: /
  port: 8081

auth-server-url: http://localhost:8080 # 授权服务地址

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: ${auth-server-url}/oauth/token #请求令牌地址
      user-authorization-uri: ${auth-server-url}/oauth/authorize #授权码地址
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token #授权token地址
