server:
  servlet:
    context-path: /
  port: 8090

spring:
  application:
    name: springboot-dubbo-provider

dubbo:
  scan:
    base-packages: com.ax.provider.service.impl
  application:
    name: springboot-dubbo-provider #应用名
  registry:
    address: zookeeper://localhost:2181 #zookeeper地址
  protocol:
    name: springboot-dubbo-provider
    port: 20880