server:
  servlet:
    context-path: /
  port: 8080

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      # allowMultiQueries=true 允许批量更新
#      url: jdbc:mysql://localhost:3306/demo10_p1?characterEncoding=utf-8&allowMultiQueries=true
      url: jdbc:mysql://localhost:3306/ax_java_demo?characterEncoding=utf-8
      username: root
      password: root123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#  freemarker:
#    request-context-attribute: request
#    redis: false
#    enabled: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    check-template-location: true # 检查模板是否存在，然后再呈现
    enabled: true #启用MVC Thymeleaf视图分辨率
    template-resolver-order: 0
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8


  redis:
    password: # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    pool:
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    host: localhost # Redis服务器地址
    timeout: 5000 # 连接超时时间（毫秒）

#  mvc:
#    favicon:
#      enabled: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ax.demo.entity

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com.ax.demo.mapper : debug
