package com.ax.spring.mapper;

import com.ax.spring.dao.Logininfo;
import org.apache.ibatis.annotations.Param;

public interface LogininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logininfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logininfo
     *
     * @mbggenerated
     */
    int insert(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logininfo
     *
     * @mbggenerated
     */
    int insertSelective(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logininfo
     *
     * @mbggenerated
     */
    Logininfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Logininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_logininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Logininfo record);

    /*
    注册获得是否已经有了
     */
    int getCountByUsername(@Param("username") String username);
}